const ratings = [
    {
        name: "Aira Mendoza",
        suggestion: "Wireless Bluetooth Headphones",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110601/samples/man-portrait.jpg",
        comment: "Sound quality is amazing and the battery lasts all day. Super worth the price!",
        rating: 5,
    },
    {
        name: "Kevin Lopez",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110606/cld-sample-3.jpg",
        suggestion: "Minimalist Leather Wallet",
        comment: "Slim design and premium feel. Fits perfectly in my pocket.",
        rating: 4,
    },
    {
        name: "Nicole Tan",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110599/samples/smile.jpg",
        suggestion: "Smart Fitness Watch",
        comment: "Tracks my workouts accurately and the display is very clear.",
        rating: 5,
    },
    {
        name: "Daniel Cruz",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110596/samples/two-ladies.jpg",
        suggestion: "Portable Power Bank 20000mAh",
        comment: "Charges my phone multiple times. Very reliable during travel.",
        rating: 5,
    },
    {
        name: "Patricia Reyes",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110591/samples/people/bicycle.jpg",
        suggestion: "Oversized Streetwear Jacket",
        comment: "Love the fit and quality. Looks exactly like the photos.",
        rating: 4,
    },
    {
        name: "Mark Bautista",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110590/samples/people/boy-snow-hoodie.jpg",
        suggestion: "Ergonomic Office Chair",
        comment: "Very comfortable for long working hours. Easy to assemble too.",
        rating: 5,
    },
    {
        name: "Jasmine Villanueva",
        suggestion: "LED Desk Lamp",
        comment: "Bright, adjustable, and modern-looking. Perfect for my workspace.",
        rating: 4,
    },
    {
        name: "Ryan Garcia",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110590/samples/people/smiling-man.jpg",
        suggestion: "Gaming Mechanical Keyboard",
        comment: "Keys are responsive and the RGB lighting is awesome!",
        rating: 5,
    },
    {
        name: "Sophia Lim",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110590/samples/bike.jpg",
        suggestion: "Ceramic Vase Set",
        comment: "Beautiful design and high-quality finish. Great for home decor.",
        rating: 5,
    },
    {
        name: "Ethan Santos",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110589/samples/people/kitchen-bar.jpg",
        suggestion: "Crossbody Travel Bag",
        comment: "Compact but spacious. Perfect for daily use.",
        rating: 4,
    },
    {
        name: "Lara Gomez",
        suggestion: "Wireless Mouse",
        comment: "Lightweight and responsive. Perfect for my office setup.",
        rating: 5,
    },
    {
        name: "Miguel Rivera",
        suggestion: "Noise Cancelling Earbuds",
        comment: "Blocks outside noise very well and sound is crisp.",
        rating: 4,
    },
    {
        name: "Clara Dela Cruz",
        suggestion: "Stainless Steel Water Bottle",
        comment: "Keeps my drinks cold all day. Love the design!",
        rating: 5,
    },
    {
        name: "Antonio Perez",
        suggestion: "Smartphone Tripod Stand",
        comment: "Stable and easy to adjust. Perfect for content creation.",
        rating: 5,
    },
    {
        name: "Isabella Flores",
        suggestion: "Bluetooth Speaker",
        comment: "Amazing sound and bass for the size. Very portable.",
        rating: 4,
    },
    {
        name: "Samuel Tan",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110601/samples/man-on-a-street.jpg",
        suggestion: "Laptop Cooling Pad",
        comment: "Keeps my laptop cool during heavy use. Quiet and effective.",
        rating: 5,
    },
    {
        name: "Vivian Cruz",
        suggestion: "Decorative Wall Clock",
        comment: "Looks beautiful on my wall. Keeps perfect time.",
        rating: 4,
    },
    {
        name: "Julian Morales",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110600/samples/look-up.jpg",
        suggestion: "Smart LED Light Bulbs",
        comment: "Easy to connect to my smart home system. Colors are vibrant.",
        rating: 5,
    },
    {
        name: "Gabriela Santos",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110591/samples/animals/three-dogs.jpg",
        suggestion: "Travel Backpack",
        comment: "Spacious and comfortable. Multiple compartments make it practical.",
        rating: 5,
    },
    {
        name: "Oscar Lim",
        image:"https://res.cloudinary.com/dl1oaa2td/image/upload/v1769110591/samples/people/jazz.jpg",
        suggestion: "Adjustable Standing Desk",
        comment: "Easy to adjust height. Very sturdy and modern design.",
        rating: 4,
    },
];




export default ratings;